---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  version: "1.20"

availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

fargateProfiles:
  - name: fp-fargate1
    selectors:
      - namespace: kube-system
      - namespace: default
      - namespace: fargate
      - namespace: storage
      - namespace: rbac-test
  - name: fp-fargate2
    selectors:
      - namespace: development
      - namespace: integration
      - namespace: gatekeeper-system
      - namespace: amazon-cloudwatch

#managedNodeGroups:
#- name: nodegroup
#  desiredCapacity: 3

# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true

addons:
- name: vpc-cni
  version: latest
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: kube-proxy
  version: latest
- name: coredns
  version: latest